nosana:
  description: dotnet build

global:
  image: registry.hub.docker.com/_/microsoft-dotnet-nightly-sdk:7.0

  trigger:
    branch:
      - master

jobs:
  - name: build
    commands:
      - dotnet build
    artifacts:
      - name: dotnet
        path: ./dotnet/

  - name: test
    commands:
      - dotnet test
    resources:
      - name: dotnet
        path: ./dotnet/
