nosana:
  description: dotnet build

global:
  image: mcr.microsoft.com/dotnet/nightly/sdk:7.0

  trigger:
    branch:
      - master

jobs:
  - name: build
    commands:
      - dotnet build -c Release
    artifacts:
      - name: dotnet
        path: ./dotnet/

  - name: test
    commands:
      - dotnet test
    resources:
      - name: dotnet
        path: ./dotnet/
