nosana:
  description: dotnet build

global:
  image: mcr.microsoft.com/dotnet/nightly/sdk:6.0

  trigger:
    branch:
      - master

jobs:
  - name: build & test
    commands:
      - dotnet test -c Release
