version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - ../orkadweb.production.env
    environment:
      ASPNETCORE_ENVIRONMENT: production
      ConnectionStrings:OrkadWeb: Server=db;Database=orkadweb;Uid=root;Pwd=production

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: orkadweb
      MYSQL_ROOT_PASSWORD: production
