name: Angular

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'OrkadWeb.Angular/ClientApp/package-lock.json'
    - run: npm ci
      working-directory: OrkadWeb.Angular/ClientApp/
    - run: npm run build --if-present
      working-directory: OrkadWeb.Angular/ClientApp/
    #- run: npm test
    #  working-directory: OrkadWeb.Angular/ClientApp/
